apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm-semantic-router.fullname" . }}-hf-token
  labels:
    app.kubernetes.io/name: semantic-router
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: router
type: Opaque
data:
  token: {{ .Values.semanticRouter.hfToken | default "" | b64enc | quote }}
